default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: reporting_development

test:
  <<: *default
  database: reporting_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

prodcution:
  url: <%= ENV['DATABASE_URL'] %>
